spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:3306/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# To run: SPRING_PROFILES_ACTIVE=test
# Set the following environment variables before running:
# export RDS_HOSTNAME=product-service.cnwagymg8eyz.ap-south-1.rds.amazonaws.com
# export RDS_DB_NAME=productdb
# export RDS_USERNAME=admin
# export RDS_PASSWORD=your_password