spring:
  datasource:
    url: jdbc:mysql://aurora-endpoint:3306/product
    username: master
    password: selfmanaged
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'

# to enable: SPRING_PROFILES_ACTIVE=test

