cloud:
  aws:
    region: ${CLOUD_AWS_REGION:ap-south-1}
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY:}
      secret-key: ${CLOUD_AWS_SECRET_KEY:}

app:
  secret:
    # Secret name/ARN in AWS Secrets Manager
    name: ${APP_SECRET_NAME:productdb}

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
